#!/usr/bin/env node

/**
 * TodoLang Build System
 *
 * This script provides the build pipeline for compiling TodoLang source files
 * to JavaScript and creating the final application bundle.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Build configuration
const config = {
  srcDir: path.join(__dirname, 'src'),
  distDir: path.join(__dirname, 'dist'),
  appDir: path.join(__dirname, 'src', 'app'),
  languageDir: path.join(__dirname, 'src', 'language'),
  frameworkDir: path.join(__dirname, 'src', 'framework'),

  // File extensions
  todoLangExt: '.todolang',
  jsExt: '.js',

  // Build modes
  development: process.argv.includes('--dev'),
  production: process.argv.includes('--production'),
  minify: process.argv.includes('--minify'),
  sourceMaps: process.argv.includes('--source-maps'),
  watch: process.argv.includes('--watch')
};

class TodoLangBuilder {
  constructor(config) {
    this.config = config;
    this.compiler = null; // Will be loaded when needed
  }

  async init() {
    console.log('🚀 Initializing TodoLang Build System...');

    // Ensure dist directory exists
    if (!fs.existsSync(this.config.distDir)) {
      fs.mkdirSync(this.config.distDir, { recursive: true });
    }

    // Load compiler when it's implemented
    try {
      const { TodoLangCompiler } = await import('./src/language/compiler/index.js');
      this.compiler = new TodoLangCompiler();
      console.log('✅ TodoLang compiler loaded');
    } catch (error) {
      console.log('⚠️  TodoLang compiler not yet implemented, using placeholder');
      this.compiler = new PlaceholderCompiler();
    }
  }

  async build() {
    console.log('🔨 Starting TodoLang build process...');

    try {
      // Step 1: Compile TodoLang files
      await this.compileTodoLangFiles();

      // Step 2: Bundle framework and runtime
      await this.bundleFramework();

      // Step 3: Create HTML template
      await this.createHTMLTemplate();

      // Step 4: Copy assets
      await this.copyAssets();

      console.log('✅ Build completed successfully!');

      if (this.config.watch) {
        this.startWatcher();
      }

    } catch (error) {
      console.error('❌ Build failed:', error.message);
      process.exit(1);
    }
  }

  async compileTodoLangFiles() {
    console.log('📝 Compiling TodoLang files...');

    const todoLangFiles = this.findTodoLangFiles(this.config.appDir);

    for (const file of todoLangFiles) {
      const relativePath = path.relative(this.config.srcDir, file);
      const outputPath = path.join(
        this.config.distDir,
        relativePath.replace(this.config.todoLangExt, this.config.jsExt)
      );

      console.log(`  Compiling: ${relativePath}`);

      const sourceCode = fs.readFileSync(file, 'utf8');
      const compiledCode = await this.compiler.compile(sourceCode, file);

      // Ensure output directory exists
      const outputDir = path.dirname(outputPath);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      fs.writeFileSync(outputPath, compiledCode);

      if (this.config.sourceMaps) {
        // Generate source maps when implemented
        console.log(`    Generated source map for ${relativePath}`);
      }
    }
  }

  async bundleFramework() {
    console.log('📦 Bundling framework and runtime...');

    // Create a bundle that includes all framework components
    const frameworkFiles = [
      path.join(this.config.languageDir, 'runtime', 'index.js'),
      path.join(this.config.frameworkDir, 'state', 'index.js'),
      path.join(this.config.frameworkDir, 'components', 'index.js'),
      path.join(this.config.frameworkDir, 'router', 'index.js'),
      path.join(this.config.frameworkDir, 'storage', 'index.js')
    ];

    let bundleContent = '// TodoLang Framework Bundle\n';
    bundleContent += '// Generated by TodoLang Build System\n\n';

    for (const file of frameworkFiles) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf8');
        const relativePath = path.relative(this.config.srcDir, file);
        bundleContent += `// === ${relativePath} ===\n`;
        bundleContent += content + '\n\n';
      }
    }

    const bundlePath = path.join(this.config.distDir, 'todolang-framework.js');
    fs.writeFileSync(bundlePath, bundleContent);

    if (this.config.minify) {
      console.log('🗜️  Minifying bundle...');
      // Minification would be implemented here
    }
  }

  async createHTMLTemplate() {
    console.log('📄 Creating HTML template...');

    const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TodoLang Todo Application</title>
    <style>
        /* Basic styling for the todo app */
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }

        .todo-app {
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 30px;
        }

        .todo-input {
            width: 100%;
            padding: 12px;
            border: 2px solid #ddd;
            border-radius: 4px;
            font-size: 16px;
            margin-bottom: 20px;
        }

        .todo-item {
            display: flex;
            align-items: center;
            padding: 10px;
            border-bottom: 1px solid #eee;
        }

        .todo-item.completed {
            opacity: 0.6;
            text-decoration: line-through;
        }

        .todo-filters {
            display: flex;
            justify-content: center;
            gap: 10px;
            margin-top: 20px;
        }

        .filter-btn {
            padding: 8px 16px;
            border: 1px solid #ddd;
            background: white;
            border-radius: 4px;
            cursor: pointer;
        }

        .filter-btn.active {
            background: #007bff;
            color: white;
        }
    </style>
</head>
<body>
    <div id="app">
        <div class="todo-app">
            <h1>Loading TodoLang Application...</h1>
            <p>Please wait while the TodoLang runtime initializes.</p>
        </div>
    </div>

    <!-- TodoLang Framework -->
    <script src="todolang-framework.js"></script>

    <!-- Compiled Application -->
    <script src="app/components/index.js"></script>
    <script src="app/models/index.js"></script>
    <script src="app/services/index.js"></script>

    <!-- Application Bootstrap -->
    <script>
        // Initialize TodoLang application when DOM is ready
        document.addEventListener('DOMContentLoaded', function() {
            console.log('🚀 Starting TodoLang Application...');

            // This will be replaced with actual TodoLang runtime initialization
            // when the compiler and runtime are implemented
            const appElement = document.getElementById('app');
            appElement.innerHTML = \`
                <div class="todo-app">
                    <h1>TodoLang Todo Application</h1>
                    <p><strong>Status:</strong> Framework and compiler are being built...</p>
                    <p>This placeholder will be replaced with the actual TodoLang application once tasks 2-16 are completed.</p>
                    <div class="todo-input-placeholder">
                        <input type="text" class="todo-input" placeholder="Add a new todo (placeholder)" disabled>
                    </div>
                    <div class="todo-list-placeholder">
                        <div class="todo-item">
                            <input type="checkbox" disabled> Sample todo item (placeholder)
                        </div>
                    </div>
                    <div class="todo-filters">
                        <button class="filter-btn active">All</button>
                        <button class="filter-btn">Active</button>
                        <button class="filter-btn">Completed</button>
                    </div>
                </div>
            \`;
        });
    </script>
</body>
</html>`;

    const htmlPath = path.join(this.config.distDir, 'index.html');
    fs.writeFileSync(htmlPath, htmlTemplate);
  }

  async copyAssets() {
    console.log('📁 Copying assets...');

    // Copy any additional assets (CSS, images, etc.)
    // This would be expanded as needed
  }

  findTodoLangFiles(dir) {
    const files = [];

    if (!fs.existsSync(dir)) {
      return files;
    }

    const items = fs.readdirSync(dir);

    for (const item of items) {
      const fullPath = path.join(dir, item);
      const stat = fs.statSync(fullPath);

      if (stat.isDirectory()) {
        files.push(...this.findTodoLangFiles(fullPath));
      } else if (item.endsWith(this.config.todoLangExt)) {
        files.push(fullPath);
      }
    }

    return files;
  }

  startWatcher() {
    console.log('👀 Starting file watcher...');

    // Simple file watcher implementation
    // In a real implementation, this would use a proper file watching library
    console.log('File watching would be implemented here for development mode');
  }
}

// Placeholder compiler for when the real compiler isn't implemented yet
class PlaceholderCompiler {
  async compile(sourceCode, filePath) {
    const relativePath = path.relative(process.cwd(), filePath);

    return `// Compiled from: ${relativePath}
// This is a placeholder - the actual TodoLang compiler will be implemented in task 4

console.log('TodoLang file compiled: ${relativePath}');

// Original TodoLang source (as comment):
/*
${sourceCode}
*/

// Placeholder JavaScript code
export default {
  type: 'TodoLangPlaceholder',
  source: '${relativePath}',
  compiled: true
};`;
  }
}

// CLI interface
async function main() {
  const builder = new TodoLangBuilder(config);

  if (process.argv.includes('--help')) {
    console.log(`
TodoLang Build System

Usage: node build.js [options]

Options:
  --dev              Development build
  --production       Production build
  --minify          Minify output
  --source-maps     Generate source maps
  --watch           Watch for file changes
  --help            Show this help message

Examples:
  node build.js --dev --watch
  node build.js --production --minify --source-maps
`);
    return;
  }

  await builder.init();
  await builder.build();
}

// Run if called directly
if (process.argv[1] && process.argv[1].endsWith('build.js')) {
  main().catch(error => {
    console.error('Build system error:', error);
    process.exit(1);
  });
}

export { TodoLangBuilder, config };